import {assertPeriodHTML} from './period-test-helpers.js';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import all from '../data/articles-supplemental.json' with {type:'json'};
import icons from '../data/game-app-icons.json' with {type:'json'};
import ledger from '../data/game-code-candidates.json' with {type:'json'};
import {validateGameCouponLayout} from '../src/game-code-layout-contract.js';
import {validateGameFeaturedImage} from '../src/game-featured-image-policy.js';
import {validateGameCandidateCoverage} from '../src/game-code-candidate-policy.js';
import {validateArticleDraft} from '../tools/validate-article-draft.mjs';
const key='cat-gunner-codes-202610',article=all.find(a=>a.articleKey===key);
test('Cat Gunner publishes 38 unique source-traced copy codes and 12 ledger candidates',()=>{
 assert.ok(article);
 const html=readFileSync(new URL('../drafts/'+key+'.html',import.meta.url),'utf8').trim();
 const draft=JSON.parse(readFileSync(new URL('../drafts/'+key+'.json',import.meta.url),'utf8'));
 assert.deepEqual(draft.post,article.post);
 assert.equal(html,article.post.content);
 assert.equal(article.post.labels.includes('총잡이 고양이'),true);
 assert.equal(article.source.officiallyVerifiedCodeCount,0);
 assert.equal((html.match(/data-ncp-copy=/g)||[]).length,38);
 assert.equal((html.match(/class="ncp-code-card" role="row"/g)||[]).length,38);
  assertPeriodHTML(html);
 const codes=[...html.matchAll(/data-ncp-copy="([^"]+)"/g)].map(x=>x[1]);
 assert.equal(new Set(codes).size,38);
 for(const row of ledger.filter(x=>x.gameName==='총잡이 고양이'))assert.ok(codes.includes(row.code),'missing '+row.code);
 assert.equal(html.includes('ILOVECAT 쿠폰 복사'),false);
 assert.equal(validateGameCouponLayout(key,article.post),true);
 assert.equal(validateGameCandidateCoverage(article),true);
 assert.equal(validateArticleDraft(article),true);
});
test('Cat Gunner uses official App Store icon and no duplicated Blogger title',()=>{
 const app=icons.find(x=>x.articleKey===key);
 assert.equal(app?.gameName,'총잡이 고양이');
 assert.ok(app.appStoreUrl.includes('id6764201639'));
 assert.ok(app.iconUrl.includes('512x512bb.jpg'));
 assert.equal(validateGameFeaturedImage(key,article.post),true);
 assert.equal((article.post.content.match(/data-ncp-featured-image=/g)||[]).length,1);
 assert.equal((article.post.content.match(/<!--more-->/g)||[]).length,1);
 assert.equal(article.post.content.includes('<h1'),false);
 assert.equal(article.post.content.includes(article.post.title),false);
});
test('separates unverified candidates and unknown in-game redemption from claims of success',()=>{
 const html=article.post.content;
 assert.ok(html.includes('공식 발급이 확인된 공용 코드는 없고'));
 assert.ok(html.includes('교환코드 메뉴를 확인하지 못했습니다'));
 assert.ok(html.includes('다른 게임인'));
 assert.ok(html.includes('https://game.edu.kg/'));
 assert.equal(article.source.candidates.length,38);
 assert.ok(article.source.candidates.every(c=>c.status==='UNVERIFIED'&&c.workingVerifiedAt===null));
});
