import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import coupons from '../data/coupons.json' with {type:'json'};
import {validateCoupon} from '../src/coupons.js';

const now=Date.parse('2026-10-05T12:30:00Z');

test('시바 모험단 공식 쿠폰 후보는 UNVERIFIED로 유효하고 ACTIVE가 아니다',()=>{
  const coupon=coupons.find(x=>x.id==='shibarpg-pick7p2y');
  assert.ok(coupon);
  assert.equal(coupon.status,'UNVERIFIED');
  assert.equal(coupon.code,'pick7p2y');
  assert.equal(coupon.expiresAt,'2026-10-06T00:00:00.000Z');
  assert.equal(coupon.rewards[0].name,'시바 코인');
  assert.equal(coupon.rewards[0].quantity,10);
  assert.equal(validateCoupon(coupon,now),coupon);
});

test('시바 모험단 공개 글은 쿠폰 전문사이트형 핵심 정보와 UI를 표시한다',()=>{
  const draft=JSON.parse(readFileSync(new URL('../drafts/shibarpg-pickup-202610.json',import.meta.url),'utf8'));
  const html=readFileSync(new URL('../drafts/shibarpg-pickup-202610.html',import.meta.url),'utf8');
  assert.equal(draft.publicationStatus,'LIVE');
  assert.equal(draft.publication.postId,'4686430079776725627');
  assert.equal(draft.publication.url,'https://lsifl.blogspot.com/2026/10/pick7p2y.html');
  assert.equal(draft.publication.publicVerified,false);
  assert.equal(draft.publication.workflowRunId,null);
  assert.deepEqual(draft.post.labels,['게임','시바 모험단']);
  assert.equal(draft.post.title,'시바 모험단 쿠폰 코드 모음 (2026년 10월) | 입력 방법·보상');
  assert.equal(draft.post.content,html.trim());
  assert.match(html,/pick7p2y/);
  assert.match(html,/시바 코인 10개/);
  assert.match(html,/2026년 10월 6일 오전 9시/);
  assert.match(html,/현재 확인된 쿠폰/);
  assert.doesNotMatch(html,/현재 사용 가능한 쿠폰/);
  assert.match(html,/확인된 코드/);
  assert.match(html,/만료된 쿠폰/);
  assert.match(html,/쿠폰이 안 될 때 확인/);
  assert.match(html,/새 쿠폰 확인 방법/);
  assert.match(html,/관련 게임 쿠폰/);
  assert.match(html,/자주 묻는 질문/);
  assert.match(html,/공식 출처/);
  assert.match(html,/class="ncp-quickbar"/);
  assert.match(html,/href="#ncp-active"/);
  assert.match(html,/href="#ncp-expired"/);
  assert.match(html,/공식 채널/);
  assert.match(html,/class="ncp-coupon-card"/);
  assert.match(html,/class="ncp-copy-wrap"/);
  assert.match(html,/class="ncp-copy"/);
  assert.match(html,/data-ncp-copy="pick7p2y"/);
  assert.match(html,/class="ncp-copy-state" role="status"/);
  assert.match(html,/ncp-count ncp-count-muted/);
  assert.match(html,/aria-label="만료 쿠폰 0개"/);
  assert.match(html,/\.ncp-copy\{min-height:44px/);
  assert.match(html,/\.ncp-btn\{display:inline-flex;min-height:46px/);
  assert.equal(html.includes('onclick='),false);
  assert.match(html,/<!--more-->/);
  const jump=html.indexOf('<!--more-->');
  assert.ok(jump>0);
  assert.equal(html.slice(0,jump).includes('pick7p2y'),false);
  assert.match(html,/@media \(max-width:640px\)/);
  assert.match(html,/class="ncp-help-list"/);
  assert.equal(html.includes('2713'),false);
  assert.equal(html.includes('&#10003;'),false);
  assert.equal(html.includes('content:"✓"'),false);
  assert.equal(html.includes('ncp-checklist'),false);
  assert.equal(html.includes('class="ncp-checklist"'),false);
  assert.equal(html.includes('class="ncp-check"'),false);
  assert.match(html,/coupon\.withhive\.com\/shibarpg/);
  assert.doesNotMatch(html,/실사용 미검증|UNVERIFIED|workingVerifiedAt|verificationResult|evidenceMethod|validator|쿠폰 확인 기준|운영 데이터 상태|내부 운영 상태|내부 검증 정책|게임 보상은 현금 가치로 환산하지 않습니다|개인정보 처리 안내|전체 계정에서 사용 가능|검증 완료/);
});
