import {icons as svgIcons} from './site-icons.mjs';
const icons=['gamepad-2','smartphone','monitor','plane','heart','shield','graduation-cap'];
export function homeR4(categories){
  const nav=categories.map((name,i)=>`<a class='ncp-r4-category' href='/search/label/${encodeURIComponent(name)}'><span>${svgIcons[icons[i]]}</span>${name}</a>`).join('');
  return `<b:if cond='data:view.isHomepage'><div class='ncp-r4' id='ncp-home-r4'><header class='ncp-r4-wrap ncp-r4-top'><a class='ncp-r4-logo' href='/'>아끼고 보자</a><p>필요한 쿠폰을 더 쉽게</p></header><section class='ncp-r4-hero'><div class='ncp-r4-wrap ncp-r4-hero-inner'><div><p class='ncp-r4-eyebrow'>좋은 혜택, 더 즐거운 일상!</p><h1>필요한 쿠폰,<br/>복사해서 바로 사용하세요</h1><form class='ncp-r4-search' action='/search' method='get' role='search'><input name='q' aria-label='브랜드 또는 게임 검색' placeholder='브랜드 또는 게임 이름을 검색하세요' type='search'/><button type='submit'>검색</button></form><p class='ncp-r4-sub'>게임부터 일상까지, 쿠폰과 사용 방법을 한곳에서.</p></div><picture><source srcset='https://akkigo-boja.ansqhd5774.workers.dev/home-hero.webp' type='image/webp'/><img src='https://akkigo-boja.ansqhd5774.workers.dev/home-hero.png' alt='파란 쿠폰을 든 아끼고 보자 캐릭터' width='600' height='360' fetchpriority='high'/></picture></div></section><nav class='ncp-r4-wrap ncp-r4-categories' aria-label='쿠폰 카테고리'>${nav}</nav><main class='ncp-r4-wrap' id='ncp-coupon-home'><section><div class='ncp-r4-section-head'><h2>게임</h2><a href='/search/label/${encodeURIComponent('게임')}'>전체 보기 →</a></div><div class='ncp-r4-game-list'></div><p class='ncp-r4-status' role='status' aria-live='polite'>게임 쿠폰을 불러오는 중입니다.</p></section><footer class='ncp-r4-bottom'><strong>아끼고 보자</strong><span>쿠폰별 보상·만료·사용 조건은 상세 페이지에서 확인하세요.</span><a href='/p/blog-page.html'>개인정보 처리 안내</a></footer></main></div></b:if>`;
}
export function categoryHeaderR4(categories){
 const nav=categories.map((name,i)=>`<a class='ncp-r4-category' href='/search/label/${encodeURIComponent(name)}'><span>${svgIcons[icons[i]]}</span>${name}</a>`).join('');
 return `<div class='ncp-r4 ncp-r4-category-header'><header class='ncp-r4-wrap ncp-r4-top'><a class='ncp-r4-logo' href='/'>아끼고 보자</a><form class='ncp-r4-search' action='/search' method='get' role='search'><input name='q' aria-label='브랜드 또는 게임 검색' placeholder='브랜드 또는 게임 이름을 검색하세요' type='search'/><button type='submit'>검색</button></form></header><nav class='ncp-r4-wrap ncp-r4-categories' aria-label='쿠폰 카테고리'>${nav}</nav></div>`;
}
