import {readFile,writeFile} from 'node:fs/promises';
import {escapeHtml as e} from '../src/coupons.js';
const root=new URL('../',import.meta.url);
const base=await readFile(new URL('theme/blogger-native-base.xml',root),'utf8');
const categories=['게임','여행·숙박','배달·외식','쇼핑·오픈마켓','식품·마트·편의점','뷰티·화장품','패션·신발·잡화','전자·가전·IT','건강·영양·헬스','생활·가구·인테리어','문화·공연·레저','구독·OTT','소프트웨어·AI','반려동물','육아·키즈','교육·강의','자동차·용품'];
const coupons=JSON.parse(await readFile(new URL('data/coupons.json',root),'utf8'));
const manual=coupons.filter(c=>c.verificationResult==='SUCCESS');
const links=[['제우스: 오만의 신','/2026/10/blog-post.html'],['리니지M','/2026/10/m.html'],['명조:워더링 웨이브','/2026/10/blog-post_05.html']];
const css=`
/* R3 coupon shell; native Blogger widgets remain intact. */
:root{--ncp-ink:#172033;--ncp-blue:#2457d6;--ncp-line:#e2e8f0}
body{margin:0!important;padding:0!important;background:#f4f6f8!important}.centered-top-container,.centered-top-placeholder,.sidebar-container,.bg-photo,.bg-photo-overlay{display:none!important}.page_body{padding-top:0!important}.centered{padding-top:0!important;max-width:1180px!important}.ncp-home .page{display:none!important}
.ncp-r3{font-family:Arial,'Noto Sans KR',sans-serif;color:var(--ncp-ink)}.ncp-r3 a{text-decoration:none;color:var(--ncp-blue)}.ncp-r3-wrap{max-width:1180px;margin:auto;padding:24px}.ncp-r3-header{background:#fff;border-bottom:1px solid var(--ncp-line)}.ncp-r3-head{display:flex;align-items:center;gap:24px;flex-wrap:wrap}.ncp-r3-logo{font-size:26px;font-weight:800}.ncp-r3-search{display:flex;flex:1;min-width:240px;gap:8px}.ncp-r3 input{flex:1;min-width:0;padding:13px;border:1px solid var(--ncp-line);border-radius:10px}.ncp-r3 button,.ncp-r3-link{min-height:44px;padding:12px 16px;border:0;border-radius:10px;background:var(--ncp-blue);color:white!important;font-weight:700;cursor:pointer}.ncp-r3-rail{display:flex;gap:8px;overflow-x:auto;padding-top:0}.ncp-r3-chip{white-space:nowrap;padding:10px 14px;background:#edf2ff;border-radius:22px;font-size:14px}.ncp-r3-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.ncp-r3-card{padding:24px;border:1px solid var(--ncp-line);border-radius:16px;background:white;min-width:0}.ncp-r3 h1{font-size:36px;line-height:1.3}.ncp-r3 h2{margin:28px 0 16px;font-size:24px}.ncp-r3 h3{font-size:20px}.ncp-r3 p{line-height:1.8}.ncp-r3 code{display:block;padding:16px;background:#edf2ff;border-radius:10px;font-size:22px;overflow-wrap:anywhere}.ncp-r3-badge{display:inline-block;padding:6px 10px;background:#e8f6ed;border-radius:8px;font-size:13px}.ncp-r3-muted{color:#64748b;font-size:14px}.ncp-r3-footer{border-top:1px solid var(--ncp-line);margin-top:32px;background:white}.ncp-r3-copy-state{min-height:24px}.ncp-r3-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}
@media(max-width:700px){.ncp-r3-wrap{padding:16px}.ncp-r3-grid{grid-template-columns:1fr}.ncp-r3 h1{font-size:28px}.ncp-r3-head{gap:16px}.ncp-r3-search{flex-basis:100%}.ncp-r3-card{padding:18px}.ncp-r3-rail{padding-top:0}.centered{padding:0!important}}
`;
const header=`<div class='ncp-r3'><header class='ncp-r3-header'><div class='ncp-r3-wrap ncp-r3-head'><a class='ncp-r3-logo' href='/'>아끼고 보자</a><form class='ncp-r3-search' action='/search' method='get' role='search'><input name='q' aria-label='브랜드 또는 게임 검색' placeholder='브랜드 또는 게임 검색' type='search'/><button type='submit'>검색</button></form></div><nav class='ncp-r3-wrap ncp-r3-rail' aria-label='쿠폰 카테고리'>${categories.map(c=>`<a class='ncp-r3-chip' href='/search/label/${encodeURIComponent(c)}'>${e(c)}</a>`).join('')}</nav></header></div>`;
const cards=manual.map(c=>`<article class='ncp-r3-card'><span class='ncp-r3-badge'>직접 적용 제보 1건</span><h3>${e(c.brand)}</h3><code>${e(c.code)}</code><p>등록 성공 및 보상 수령이 확인된 계정 사례입니다.</p><details><summary>보상 보기</summary><ul>${c.rewards.map(r=>`<li>${e(r.name)} ${e(r.quantity)}개</li>`).join('' )}</ul></details><p class='ncp-r3-muted'>플랫폼: 공식 웹 등록 · 서버 범위 미확인</p><p class='ncp-r3-muted'>서버 범위·전체 계정 조건·만료일 미확인<br/>확인 기록: ${e(c.workingVerifiedAt)}</p><div class='ncp-r3-actions'><button type='button' data-ncp-copy='${e(c.code)}'>코드 복사</button><a class='ncp-r3-link' href='/2026/10/blog-post.html'>보상·입력 방법</a></div><p class='ncp-r3-copy-state' role='status' aria-live='polite'></p></article>`).join('');
const home=`<b:if cond='data:view.isHomepage'><main class='ncp-r3 ncp-r3-wrap' id='ncp-coupon-home'><h1>쿠폰을 찾고, 확인하고, 사용하세요</h1><p>공식 출처와 실제 적용 기록을 구분해 안내합니다.</p><h2>직접 적용 확인 기록</h2><div class='ncp-r3-grid'>${cards||'<p>직접 적용 확인 기록이 없습니다.</p>'}</div><h2>게임 쿠폰 · 입력 안내</h2><div class='ncp-r3-grid'>${links.map(([name,url])=>`<article class='ncp-r3-card'><h3>${e(name)}</h3><p>공식 출처 · 쿠폰 조건 · 입력 안내</p><a class='ncp-r3-link' href='${url}'>확인하기</a></article>`).join('')}</div><h2>최신 코드</h2><p>전체 적용 조건이 확인된 활성 쿠폰은 아직 없습니다. 위 사용 확인 기록은 특정 계정의 사례입니다.</p><h2>만료 임박</h2><p>만료일이 확인된 쿠폰이 없습니다.</p></main></b:if>`;
const footer=`<footer class='ncp-r3 ncp-r3-footer'><div class='ncp-r3-wrap'><strong>아끼고 보자</strong><p class='ncp-r3-muted'>직접 적용 · 공식 출처 · 미검증을 구분합니다. 게임 보상은 현금 할인액으로 환산하지 않습니다.</p><a href='/p/blog-page.html'>개인정보 처리 안내</a></div></footer>`;
const script=`<script type='text/javascript'>//<![CDATA[
document.addEventListener('click',async function(event){const button=event.target.closest('[data-ncp-copy]');if(!button)return;const status=button.closest('article').querySelector('[role="status"]');try{await navigator.clipboard.writeText(button.dataset.ncpCopy);status.textContent='코드를 복사했습니다.';}catch{status.textContent='자동 복사가 제한됩니다. 위 코드를 선택해 복사하세요.';}});
//]]></script>`;
const output=base.replace(']]></b:skin>',css+']]></b:skin>').replace('<body>',`<body><b:class cond='data:view.isHomepage' name='ncp-home'/>${header}${home}`).replace('</body>',footer+script+'</body>');
await writeFile(new URL('nutriments_blogger_r1_bundle/theme/blogger-theme-r1.xml',root),output);
console.log('R3 theme generated using native Blogger widget base.');
