import research from '../data/duolingo-super-research-202610.json' with {type:'json'};
const KEY='duolingo-super-coupons-202610';
const ICON='https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/bd/c9/b8/bdc9b8e4-4ac0-7976-bf0a-c3647338fc7d/AppIcon-0-0-1x_U007epad-0-1-85-220.png/1920x1080ia-80.png';
const APP='https://apps.apple.com/kr/app/duolingo/id570060128';
const e=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const hot=['LOVELANGUAGE','SALE25','SAVE50','DRACARYS','vetv1'];
const codes=new Map(research.records.map(r=>[r.code,r]));
if(codes.size!==51||hot.some(k=>!codes.has(k)))throw Error('DUOLINGO_CODE_SOURCE_INVALID');
const featured=hot.map(k=>codes.get(k)),archive=research.records.filter(r=>!hot.includes(r.code));
const info=r=>r.status==='EXPIRED_REPORTED'?'만료·실패 보고':r.status==='CROSS_BRAND_SUSPECT'?'다른 서비스 의심':'미확인 후보';
const row=(r,i,copy)=>'<tr><td>'+String(i+1).padStart(2,'0')+'</td><td>'+(r.sourcePublishedAt||'게시일 미확인')+'</td><td><code>'+e(r.code)+'</code></td><td>'+info(r)+'</td><td><a href="'+e(r.sourceUrl)+'" rel="noopener noreferrer">원문</a>'+(copy?'<button type="button" class="ncp-copy" data-ncp-copy="'+e(r.code)+'">복사</button>':'')+'</td></tr>';
const head='<thead><tr><th>순서</th><th>출처 게시일</th><th>쿠폰</th><th>상태</th><th>출처·복사</th></tr></thead>';
const css='<style>[data-ncp-article="'+KEY+'"]{font:15px/1.7 Arial,sans-serif;color:#172033;max-width:100%;overflow-wrap:anywhere}[data-ncp-article="'+KEY+'"] *{box-sizing:border-box}[data-ncp-article="'+KEY+'"] h1{font-size:26px}[data-ncp-article="'+KEY+'"] h2{font-size:20px;margin:26px 0 10px}[data-ncp-article="'+KEY+'"] .duo-stat{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:14px 0}[data-ncp-article="'+KEY+'"] .duo-stat>div{padding:14px;background:#f3f7fd}[data-ncp-article="'+KEY+'"] .duo-alert{background:#fff8e8;border-left:3px solid #bb8d29;padding:12px}[data-ncp-article="'+KEY+'"] table{width:100%;table-layout:fixed;border-collapse:collapse;font-size:12px}[data-ncp-article="'+KEY+'"] td,[data-ncp-article="'+KEY+'"] th{border-bottom:1px solid #dfe5ed;padding:9px 6px;text-align:left}[data-ncp-article="'+KEY+'"] th{background:#f2f5fb}[data-ncp-article="'+KEY+'"] th:first-child{width:35px}[data-ncp-article="'+KEY+'"] th:nth-child(2){width:125px}[data-ncp-article="'+KEY+'"] th:nth-child(4){width:115px}[data-ncp-article="'+KEY+'"] th:last-child{width:90px}[data-ncp-article="'+KEY+'"] code{font:700 12px Consolas,monospace;overflow-wrap:anywhere}[data-ncp-article="'+KEY+'"] .ncp-copy{display:block;width:100%;margin-top:4px;min-height:38px;color:white;background:#217241;border:0;border-radius:6px;cursor:pointer}[data-ncp-article="'+KEY+'"] details{border:1px solid #dde4ed;padding:9px;border-radius:9px}[data-ncp-article="'+KEY+'"] summary{cursor:pointer;font-weight:700;padding:8px}[data-ncp-article="'+KEY+'"] .duo-table{overflow-x:auto}[data-ncp-article="'+KEY+'"] a{color:#2457d6}@media(max-width:600px){[data-ncp-article="'+KEY+'"]{font-size:13px}[data-ncp-article="'+KEY+'"] h1{font-size:22px}[data-ncp-article="'+KEY+'"] h2{font-size:18px}[data-ncp-article="'+KEY+'"] .duo-stat{grid-template-columns:1fr}[data-ncp-article="'+KEY+'"] td,[data-ncp-article="'+KEY+'"] th{padding:7px 3px;font-size:10px}[data-ncp-article="'+KEY+'"] th:first-child{width:26px}[data-ncp-article="'+KEY+'"] th:nth-child(2){width:73px}[data-ncp-article="'+KEY+'"] th:nth-child(4){width:68px}[data-ncp-article="'+KEY+'"] th:last-child{width:52px}[data-ncp-article="'+KEY+'"] code{font-size:10px}}</style>';
const preview='<div class="ncp-feed-preview" data-ncp-feed-preview="true"><div class="ncp-feed-stat"><span>공식 제휴</span><strong>Super 30일 체험</strong></div><div class="ncp-feed-stat"><span>신규 코드 발급</span><strong>10월 6일 종료</strong></div><div class="ncp-feed-stat"><span>기존 발급 코드 등록</span><strong>11월 15일까지</strong></div></div>';
const html=preview+'\n<!--more-->\n<article class="ncp-coupon-article" data-ncp-article="'+KEY+'">'+css
+'<figure data-ncp-featured-image="'+KEY+'" style="text-align:center"><a href="'+APP+'"><img data-ncp-brand-logo="true" src="'+ICON+'" alt="듀오링고 공식 Apple TestFlight 앱 아이콘" width="512" height="512" loading="eager" decoding="async" style="display:block;width:160px;height:160px;object-fit:contain;margin:auto;border-radius:18px"></a><figcaption>공식 Apple TestFlight 앱 아이콘</figcaption></figure>'
+'<h1>듀오링고 쿠폰 2026년 10월 | Super·Max 무료 체험과 할인코드</h1>'
+'<p>2026-10-10 조사 기준, 현재 한국 계정의 사용 성공이 확인된 공개 공용 코드는 없습니다. 공식 행사와 비공식 후보, 과거 만료 기록을 구분합니다.</p>'
+'<div class="duo-stat"><div><strong>30일</strong><p>공식 제휴 Super 체험</p></div><div><strong>10월 6일</strong><p>신규 발급 종료</p></div><div><strong>11월 15일</strong><p>기존 발급 코드 등록 마감</p></div></div>'
+'<h2>공식 제휴: Taco Bell × 듀오링고</h2><p>2026년 10월 1일 발표된 Super 30일 무료 프로모션입니다. 새 코드 발급은 공식 행사 페이지 기준 10월 6일 종료됐습니다. 기존에 발급받은 코드는 11월 15일까지 등록할 수 있습니다. Taco Bell Rewards 회원, 현재 유료 구독 여부, 같은 해 다른 장기 무료 체험 중복 여부 등 조건이 적용됩니다. 한국 계정 적용 여부는 미확인입니다.</p>'
+'<p><a href="https://www.tacobell.com/promotions/global-taco-day">Taco Bell 공식 행사</a> · <a href="https://www.tacobell.com/newsroom/taco-bell-and-duolingo-take-national-taco-day-global">공식 발표(2026-10-01)</a></p>'
+'<p class="duo-alert">일부 공식 보도자료 각주에는 10월 13일 발급 종료라고 적혀 있어 행사 페이지의 10월 6일 안내와 상충합니다. 새로운 발급 가능성을 확정하지 않고 공식 화면을 확인하세요. 코드는 계정별·일회용으로 제공됩니다.</p>'
+'<h2>입력해 볼 수 있는 비공식 후보 5개</h2><p>아래 문자열은 공식 현재 유효 코드라는 뜻이 아닙니다. LOVELANGUAGE·SALE25·SAVE50의 원문 최초 게시일은 미확인입니다. 지역 및 계정별 실패 가능성이 있습니다.</p>'
+'<div class="duo-table"><table>'+head+'<tbody>'+featured.map((r,i)=>row(r,i,true)).join('')+'</tbody></table></div>'
+'<h2>만료·추가 해외 문자열 46개</h2><p>중복 제거한 전체 51개 중 나머지 46개를 조사 기록으로 보존했습니다. 타 서비스와 혼동되는 문자열도 포함되어 있으며 작동 또는 공식 발급을 뜻하지 않습니다.</p>'
+'<details><summary>과거·해외 쿠폰 46개와 출처 펼치기</summary><div class="duo-table"><table>'+head+'<tbody>'+archive.map((r,i)=>row(r,i,false)).join('')+'</tbody></table></div></details>'
+'<h2>듀오링고 쿠폰 등록 방법</h2><ol><li><a href="https://www.duolingo.com/redeem">공식 교환 페이지</a>에서 로그인합니다.</li><li>코드를 정확히 입력해 적용 여부를 확인합니다.</li><li>무료 체험의 결제 수단과 종료 후 자동 갱신·취소 조건을 확인합니다.</li></ol>'
+'<h2>추가 체험 및 주의사항</h2><p><a href="https://ko.duolingo.com/">듀오링고 공식 한국어 사이트</a> 또는 앱의 무료 체험 제안을 확인하세요. 체험 기간과 계정 자격은 다를 수 있습니다. Duolingo English Test 시험 쿠폰은 Super·Max 학습 구독과 별개입니다. <a href="https://testcenter.zendesk.com/hc/ko/articles/360018677492-%EC%BF%A0%ED%8F%B0-%EC%BD%94%EB%93%9C%EB%A5%BC-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%A0%81%EC%9A%A9%ED%95%98%EB%82%98%EC%9A%94">시험 쿠폰 안내</a></p>'
+'<h2>원문 날짜·검증 기준</h2><p>기록의 날짜는 각 출처 글이나 댓글이 실제 작성된 날짜입니다. 원문이 없으면 미확인으로 두었고 수집일을 발급일로 사용하지 않았습니다. 쿠폰 복사 성공이 실제 혜택 적용을 뜻하지 않습니다. 검색량·노출률 실측 전이므로 수치나 인기 순위를 만들지 않았습니다.</p></article>';
export const duolingoArticle={articleKey:KEY,approvedForPublish:true,publicationStatus:'READY',post:{title:'듀오링고 쿠폰 2026년 10월 | Super 무료 체험·할인코드·입력 방법',labels:['교육','듀오링고'],content:html},source:{type:'DUOLINGO_GLOBAL_CROSSCHECK',url:'https://www.tacobell.com/promotions/global-taco-day',checkedAt:'2026-10-10',status:'UNVERIFIED',codes:hot,sourcePublishedAt:'2026-10-01',dateBasis:'OFFICIAL_PARTNER_NEWSROOM',searchDescription:research.seo.searchDescription,keywords:research.seo.keywords,hashtags:research.seo.hashtags}};
