name: Verify
on:
  workflow_dispatch:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: '24'
      - run: npm install --global pnpm@11.19.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm build
